import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import copy
import einops
import numpy as np

from ...utils.config import CN
from ...utils.logger import logger
from ...utils.builder import HEAD
from ...utils.misc import param_size
from ...utils.transform import inverse_sigmoid, batch_cam_extr_transf, batch_cam_intr_projection, bchw_2_bhwc, \
    denormalize
from ...utils.points_utils import sample_points_from_ball_query
from ..bricks.transformer import build_transformer
from ..layers.petr_transformer import SinePositionalEncoding3D
# from ...utils.collation import generate_grid_sample_proj
from manotorch.manolayer import ManoLayer
from pytorch3d.ops import ball_query

import imageio
import warnings
import cv2
import time
import os


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def viz_3d(image, joints_2d_proj):
    frame_1 = image.copy()
    for i in range(joints_2d_proj.shape[0]):
        cx = int(joints_2d_proj[i, 0])
        cy = int(joints_2d_proj[i, 1])
        cv2.circle(frame_1, (cx, cy), radius=1, thickness=-1, color=np.array([1.0, 0.0, 0.0]) * 255)

    img_list = [image, frame_1]
    comb_image = np.hstack(img_list)
    imageio.imwrite("tmp/img.png", comb_image)
    time.sleep(5)


def pos2posemb3d(pos, num_pos_feats=128, temperature=10000):
    scale = 2 * math.pi
    pos = pos * scale
    dim_t = torch.arange(num_pos_feats, dtype=torch.float32, device=pos.device)
    dim_t = temperature ** (2 * (torch.div(dim_t, 2, rounding_mode='floor')) / num_pos_feats)
    pos_x = pos[..., 0, None] / dim_t
    pos_y = pos[..., 1, None] / dim_t
    pos_z = pos[..., 2, None] / dim_t
    pos_x = torch.stack((pos_x[..., 0::2].sin(), pos_x[..., 1::2].cos()), dim=-1).flatten(-2)
    pos_y = torch.stack((pos_y[..., 0::2].sin(), pos_y[..., 1::2].cos()), dim=-1).flatten(-2)
    pos_z = torch.stack((pos_z[..., 0::2].sin(), pos_z[..., 1::2].cos()), dim=-1).flatten(-2)
    posemb = torch.cat((pos_y, pos_x, pos_z), dim=-1)
    return posemb


class BasePointEmbedHead(nn.Module):

    def __init__(self, cfg: CN):
        super(BasePointEmbedHead, self).__init__()
        self.cfg_transformer = cfg.TRANSFORMER
        self.cfg_position_encoding = cfg.POSITIONAL_ENCODING

        self.with_position = cfg.WITH_POSITION
        self.with_multiview = cfg.WITH_MULTIVIEW
        self.num_query = cfg.NUM_QUERY  # should equal to the n_vertices + n_joints,
        self.depth_num = cfg.DEPTH_NUM
        self.position_dim = 3 * self.depth_num
        self.position_range = cfg.POSITION_RANGE
        self.LID = cfg.LID
        self.depth_start = cfg.DEPTH_START
        self.depth_end = cfg.DEPTH_END
        self.embed_dims = cfg.EMBED_DIMS
        self.in_channels = cfg.IN_CHANNELS
        self.num_preds = cfg.NUM_PREDS

        # custom args
        self.center_shift = cfg.get("CENTER_SHIFT", False)

        self._build_head_module()
        self.init_weights()
        logger.info(f"{type(self).__name__} has {param_size(self)}M parameters, "
                    f"and got custom args: {self._str_custom_args()}")

    def _str_custom_args(self):
        return (f"center_shift: {self.center_shift}")

    def _build_head_module(self):
        self.center_shift_layer = nn.Sequential(nn.Linear(self.num_query, self.num_query), nn.ReLU(),
                                                nn.Linear(self.num_query, 1))

        self.positional_encoding = SinePositionalEncoding3D(num_feats=self.cfg_position_encoding.NUM_FEATS,
                                                            normalize=self.cfg_position_encoding.NORMALIZE)
        self.transformer = build_transformer(self.cfg_transformer)

        self.input_proj = nn.Conv2d(self.in_channels, self.embed_dims, kernel_size=1)
        self.reg_branches = nn.ModuleList()
        for i in range(self.num_preds):
            reg_branch = nn.Sequential(nn.Linear(self.pt_feat_dim, self.pt_feat_dim), nn.ReLU(),
                                       nn.Linear(self.pt_feat_dim, 3))
            self.reg_branches.append(reg_branch)

        self.adapt_pos3d = nn.Conv2d(self.embed_dims * 3 // 2, self.embed_dims, kernel_size=1, stride=1, padding=0)
        self.position_encoder = nn.Sequential(
            nn.Conv2d(self.position_dim, self.embed_dims * 2, kernel_size=1, stride=1, padding=0),
            nn.ReLU(),
            nn.Conv2d(self.embed_dims * 2, self.embed_dims, kernel_size=1, stride=1, padding=0),
        )
        self.reference_embed = nn.Embedding(self.num_query, self.embed_dims)
        self.query_embedding = nn.Sequential(
            nn.Linear(6 + (self.embed_dims * 3 // 2), self.embed_dims),
            nn.ReLU(),
            nn.Linear(self.embed_dims, self.pt_feat_dim),
        )

    def position_embeding(self, inputs, masks=None):
        eps = 1e-5
        inp_img_h, inp_img_w = inputs['inp_img_shape']
        img_feat = inputs['mlvl_feat']  # (B, N, C, H, W)
        B, N, C, H, W = img_feat.shape
        coords_h = torch.arange(H, device=img_feat.device).float() * inp_img_h / H  # U
        coords_w = torch.arange(W, device=img_feat.device).float() * inp_img_w / W  # V

        if self.LID:
            index = torch.arange(start=0, end=self.depth_num, step=1, device=img_feat.device).float()
            index_plus1 = index + 1
            bin_size = (self.depth_end - self.depth_start) / (self.depth_num * (1 + self.depth_num))
            coords_d = self.depth_start + bin_size * index * index_plus1
        else:
            index = torch.arange(start=0, end=self.depth_num, step=1, device=img_feat.device).float()
            bin_size = (self.depth_end - self.depth_start) / self.depth_num
            coords_d = self.depth_start + bin_size * index

        D = coords_d.shape[0]

        # (W, H, D, 3)
        coords = torch.stack(torch.meshgrid([coords_w, coords_h, coords_d], indexing='ij')).permute(1, 2, 3, 0)

        # ===== 1. using camera intrinsic to convert UVD 2 XYZ  >>>>>>
        INTR = inputs["cam_intr"]  # (B, N, 3, 3)
        fx = INTR[..., 0, 0].unsqueeze(dim=-1)  # (B, N, 1)
        fy = INTR[..., 1, 1].unsqueeze(dim=-1)  # (B, N, 1)
        cx = INTR[..., 0, 2].unsqueeze(dim=-1)  # (B, N, 1)
        cy = INTR[..., 1, 2].unsqueeze(dim=-1)  # (B, N, 1)
        cam_param = torch.cat((fx, fy, cx, cy), dim=-1)  # (B, N, 4)
        cam_param = cam_param.view(B, N, 1, 1, 1, 4).repeat(1, 1, W, H, D, 1)  # (B, N, W, H, D, 4)

        coords_uv, coords_d = coords[..., :2], coords[..., 2:3]  # (W, H, D, 2), (W, H, D, 1)
        coords_uv_raw = coords_uv.view(1, 1, W, H, D, 2).repeat(B, N, 1, 1, 1, 1)  # (B, N, W, H, D, 2)
        coords_d = coords_d.view(1, 1, W, H, D, 1).repeat(B, N, 1, 1, 1, 1)  # (B, N, W, H, D, 1)

        coords_uv = (coords_uv_raw - cam_param[..., 2:4]) / cam_param[..., :2]  # (B, N, W, H, D, 2)
        coords_xy = coords_uv * coords_d
        coords_z = coords_d
        coords = torch.cat((coords_xy, coords_z), dim=-1)  # (B, N, W, H, D, 3)

        # ===== 2. using camera extrinsic to transfer childs' XYZ 2 parent's space >>>>>>
        EXTR = inputs["cam_extr"]  # (B, N, 4, 4)
        coords = torch.cat((coords, torch.ones_like(coords[..., :1])), -1)
        coords = coords.unsqueeze(-1)  # (B, N, W, H, D, 4, 1)
        EXTR = EXTR.view(B, N, 1, 1, 1, 4, 4).repeat(1, 1, W, H, D, 1, 1)  # (B, N, W, H, D, 4, 4)
        coords3d = torch.matmul(EXTR, coords).squeeze(-1)[..., :3]  # (B, N, W, H, D, 3),  xyz in parent's space

        coords3d_absolute = copy.deepcopy(coords3d)
        # ===== 3. using position range to normalize coords3d
        #                 0     1     2     3     4     5
        # position_range [xmin, ymin, zmin, xmax, ymax, zmax]
        coords3d[..., 0:1] = (coords3d[..., 0:1] - self.position_range[0]) / \
                             (self.position_range[3] - self.position_range[0])
        coords3d[..., 1:2] = (coords3d[..., 1:2] - self.position_range[1]) / \
                             (self.position_range[4] - self.position_range[1])
        coords3d[..., 2:3] = (coords3d[..., 2:3] - self.position_range[2]) / \
                             (self.position_range[5] - self.position_range[2])

        coords_mask = (coords3d > 1.0) | (coords3d < 0.0)  # (B, N, W, H, D, 3)

        # coords_mask = coords_mask.flatten(-2).sum(-1) > (D * 0.5)  # (B, N, W, H)
        # coords_mask = masks | coords_mask.permute(0, 1, 3, 2)  # (B, N, H, W)
        coords3d_feat = coords3d.permute(0, 1, 4, 5, 3, 2).contiguous().view(B * N, -1, H, W)  # (B*N, 3*D, H, W)
        coords3d_feat = inverse_sigmoid(coords3d_feat)
        coords_position_embeding = self.position_encoder(coords3d_feat)  # res: (B*N, 256, H, W), 256 is self.embed_dims

        return coords_position_embeding.view(B, N, self.embed_dims, H, W), coords3d, coords3d_absolute, coords_mask

    def init_weights(self):
        # The initialization for transformer is important, we leave it to the child class to decide.
        ### self.transformer.init_weights()
        nn.init.uniform_(self.reference_embed.weight.data, 0, 1)

    def forward(self, mlvl_feat, img_metas, reference_points, template_mesh, **kwargs):
        raise NotImplementedError(f"forward not implemented in base BasePointEmbedHead")


@HEAD.register_module()  # ptemb
class POEM_PositionEmbeddedAggregationHead(BasePointEmbedHead):

    def __init__(self, cfg: CN):
        self.nsample = cfg.N_SAMPLE
        self.radius = cfg.RADIUS_SAMPLE
        self.pt_feat_dim = cfg.POINTS_FEAT_DIM
        self.init_pt_feat_dim = cfg.INIT_POINTS_FEAT_DIM  # 8
        super(POEM_PositionEmbeddedAggregationHead, self).__init__(cfg)

    def _build_head_module(self):
        super(POEM_PositionEmbeddedAggregationHead, self)._build_head_module()
        self.transition_up = nn.Linear(self.init_pt_feat_dim, self.pt_feat_dim)
        logger.warning(f"{type(self).__name__} build done")

    def _str_custom_args(self):
        str_ = super(POEM_PositionEmbeddedAggregationHead, self)._str_custom_args()
        return str_ + ", " + f"init_pt_feat_dim: {self.init_pt_feat_dim}"

    def forward(self, mlvl_feat, img_metas, reference_points, template_mesh, **kwargs):
        results = dict()
        x = mlvl_feat
        batch_size, num_cams = x.size(0), x.size(1)

        inp_img_w, inp_img_h = img_metas["inp_img_shape"]  # (256, 256)
        ref_mesh_gt = img_metas["ref_mesh_gt"]
        inp_res = torch.Tensor([inp_img_w, inp_img_h]).to(x.device).float()
        masks = x.new_zeros((batch_size, num_cams, inp_img_h, inp_img_w))
        x = self.input_proj(x.flatten(0, 1))
        x = x.view(batch_size, num_cams, *x.shape[-3:])  # [B, N, 256, H, W]
        feat_dim = x.size(2)
        assert feat_dim == self.pt_feat_dim, \
            f"self.pt_feat_dim {self.pt_feat_dim} should be equal to feat_dim {feat_dim}"
        # interpolate masks to have the same spatial shape with x
        masks = F.interpolate(masks, size=x.shape[-2:]).to(torch.bool)

        coords_embed, coords3d, coords3d_abs, _ = self.position_embeding(mlvl_feat, img_metas, masks)

        sin_embed = self.positional_encoding(masks)
        sin_embed = self.adapt_pos3d(sin_embed.flatten(0, 1)).view(x.size())  # (B, N, 256, H, W)

        posi_embed = sin_embed + coords_embed
        x = x + posi_embed

        center_point = reference_points.mean(1).unsqueeze(1)  # [B, 1, 3]
        if self.center_shift == True:
            center_point = center_point + 0.01 * \
                           self.center_shift_layer(reference_points.transpose(1, 2)).transpose(1, 2)

        # x3d = self.input_proj_3Daware(x.flatten(0, 1))  # (BN, F*D, H, W)
        x3d = x.reshape(batch_size, num_cams, -1, self.depth_num, *x.shape[-2:])  # (B, N, F*D/D, D, H, W)
        x3d = x3d.permute(0, 1, 5, 4, 3, 2).contiguous()  # (B, N, W, H, D, F)
        assert x3d.shape[-1] == self.init_pt_feat_dim, \
            f"self.init_pt_feat_dim {self.init_pt_feat_dim} should be equal to x3d's last dim {x3d.shape[-1]}"

        reference_embed = self.reference_embed.weight  # (799, 3)
        reference_embed = pos2posemb3d(reference_embed)  # (799, 384)   384 <-- (self.embed_dims * 3 // 2)
        reference_embed = reference_embed.unsqueeze(0).expand(batch_size, -1, -1)  # (B, 799, 384)
        template_mesh = template_mesh.unsqueeze(0).expand(batch_size, -1, -1)  # template mesh  # (B, 799, 3)

        # *  normalize reference points into position range
        reference_points[..., 0:1] = (reference_points[..., 0:1] - self.position_range[0]) / \
                                     (self.position_range[3] - self.position_range[0])
        reference_points[..., 1:2] = (reference_points[..., 1:2] - self.position_range[1]) / \
                                     (self.position_range[4] - self.position_range[1])
        reference_points[..., 2:3] = (reference_points[..., 2:3] - self.position_range[2]) / \
                                     (self.position_range[5] - self.position_range[2])

        query_embeds = self.query_embedding(torch.cat([
            reference_embed,
            reference_points,
            template_mesh,
        ], dim=-1))  # (B, 799, embed_dims=32)

        # coords3d_abs: [B, N, 32, 32, 32, 3], --> [B, M, 3]
        coords3d_abs = coords3d_abs.reshape(batch_size, -1, 3)
        x3d = x3d.reshape(batch_size, -1, self.init_pt_feat_dim)
        randlist = torch.randperm(coords3d_abs.size(1))
        coords3d_abs = coords3d_abs[:, randlist, :]
        x3d = x3d[:, randlist, :]

        #  [B, nsample, 3],  [B, nsample, 32]
        pt_xyz, x3d_nsample = sample_points_from_ball_query(pt_xyz=coords3d_abs,
                                                            pt_feats=x3d,
                                                            center_point=center_point,
                                                            k=self.nsample,
                                                            radius=self.radius)

        pt_feats = self.transition_up(x3d_nsample)
        pt_xyz[..., 0:1] = (pt_xyz[..., 0:1] - self.position_range[0]) / \
                           (self.position_range[3] - self.position_range[0])
        pt_xyz[..., 1:2] = (pt_xyz[..., 1:2] - self.position_range[1]) / \
                           (self.position_range[4] - self.position_range[1])
        pt_xyz[..., 2:3] = (pt_xyz[..., 2:3] - self.position_range[2]) / \
                           (self.position_range[5] - self.position_range[2])

        interm_ref_pts = self.transformer(
            pt_xyz=pt_xyz,  # [B, 2048, 3]
            pt_feats=pt_feats,  # [B, 2048, 256]
            query_emb=query_embeds,  # [B, 799, 256]
            query_xyz=reference_points,  # [B, 799, 3]
            reg_branches=self.reg_branches,
        )

        interm_ref_pts = torch.nan_to_num(interm_ref_pts)
        all_coords_preds = interm_ref_pts  # (N_Decoder, BS, NUM_QUERY, 3)

        # scale all the joitnts and vertices to the camera space
        # position_range [xmin, ymin, zmin, xmax, ymax, zmax]
        all_coords_preds[..., 0:1] = \
            all_coords_preds[..., 0:1] * (self.position_range[3] - self.position_range[0]) + self.position_range[0]
        all_coords_preds[..., 1:2] = \
            all_coords_preds[..., 1:2] * (self.position_range[4] - self.position_range[1]) + self.position_range[1]
        all_coords_preds[..., 2:3] = \
            all_coords_preds[..., 2:3] * (self.position_range[5] - self.position_range[2]) + self.position_range[2]

        results["all_coords_preds"] = all_coords_preds
        return results


@HEAD.register_module()  # proj_selfagg
class POEM_Projective_SelfAggregation_Head(BasePointEmbedHead):

    def __init__(self, cfg: CN):
        self.nsample = cfg.N_SAMPLE
        self.radius = cfg.RADIUS_SAMPLE
        self.pt_feat_dim = cfg.POINTS_FEAT_DIM
        self.merge_mode = cfg.get("CAM_FEAT_MERGE", "sum")
        self.query_type = cfg.get("QUERY_TYPE", "KPT")
        # POEM: I cat V_tmpl cat V_init
        # KPT: I
        # MVP: g + I
        # METRO: g cat V_tmpl
        super(POEM_Projective_SelfAggregation_Head, self).__init__(cfg)

    def _build_head_module(self):
        super(POEM_Projective_SelfAggregation_Head, self)._build_head_module()
        self.merge_net_feature = nn.ModuleList()
        self.merge_net_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims, self.embed_dims), nn.ReLU(),
                          nn.Linear(self.embed_dims, self.embed_dims // 2)))
        self.merge_net_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims // 2, self.embed_dims // 2), nn.ReLU(),
                          nn.Linear(self.embed_dims // 2, self.embed_dims)))
        self.merge_net_query_feature = nn.ModuleList()
        self.merge_net_query_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims, self.embed_dims), nn.ReLU(),
                          nn.Linear(self.embed_dims, self.embed_dims // 2)))
        self.merge_net_query_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims // 2, self.embed_dims // 2), nn.ReLU(),
                          nn.Linear(self.embed_dims // 2, self.embed_dims)))

        self.layer_global_feat = nn.Linear(512, self.embed_dims)
        if self.query_type == "POEM":
            self.query_embedding = nn.Sequential(
                nn.Linear(6 + self.embed_dims, self.embed_dims),
                nn.ReLU(),
                nn.Linear(self.embed_dims, self.pt_feat_dim),
            )
        elif self.query_type == "KPT":
            self.query_embedding = nn.Sequential(
                nn.Linear(self.embed_dims, self.embed_dims),
                nn.ReLU(),
                nn.Linear(self.embed_dims, self.pt_feat_dim),
            )
        elif self.query_type == "MVP":
            self.query_embedding = nn.Sequential(
                nn.Linear(self.embed_dims, self.embed_dims),
                nn.ReLU(),
                nn.Linear(self.embed_dims, self.pt_feat_dim),
            )
        elif self.query_type == "METRO":
            self.query_embedding = nn.Sequential(
                nn.Linear(self.embed_dims + 3, self.embed_dims),
                nn.ReLU(),
                nn.Linear(self.embed_dims, self.pt_feat_dim),
            )
        else:
            raise ValueError(f"no such query_type: {self.query_type}")
        logger.info(f"{type(self).__name__} got query_type: {self.query_type}")
        logger.warning(f"{type(self).__name__} build done")

    def _str_custom_args(self):
        str_ = super()._str_custom_args()
        return str_ + ", " + f"agg_merge_mode: {self.merge_mode}"

    def merge_features(self, q, merge_net, master_id, batch_size):
        """
            q: [B, nsample, N, 256]
            q_merged: [B, nsample, 256]
        """
        master_is_zero = torch.sum(master_id)
        assert master_is_zero == 0, "only support master_id is 0"
        q1 = q[:, :, 0, :]
        q = merge_net[0](q)
        master_features = q[:, :, 0, :]  # [B, nsample, 128]
        other_features = q[:, :, 1:, :]  # [B, nsample, 7, 128]
        q = torch.matmul(other_features, master_features.unsqueeze(-1))  # [B, nsample, 7, 1]
        q = torch.matmul(other_features.transpose(2, 3), q).squeeze(-1)
        q_merged = merge_net[1](q)  # [B, nsample, 256]
        q_merged = q1 + q_merged
        return q_merged

    def sample_points_from_ball_query(self, pt_xyz, center_point, k, radius):
        _, ball_idx, xyz = ball_query(center_point, pt_xyz, K=k, radius=radius, return_nn=True)
        invalid = torch.sum(ball_idx == -1) > 0
        if invalid:
            # NOTE: sanity check based on bugs reported Oct. 24
            logger.warning(f"ball query returns {torch.sum(ball_idx == -1)} / {torch.numel(ball_idx)} -1 in its index, "
                           f"which means you need to increase raidus or decrease K")
        xyz = xyz.squeeze(1)
        return xyz

    def generate_query(self, reference_embed, reference_points, template_mesh, global_feat):
        if self.query_type == "POEM":
            query_embeds = self.query_embedding(torch.cat([
                reference_embed,
                reference_points,
                template_mesh,
            ], dim=-1))  # (B, 799, pt_feat_dim)
        elif self.query_type == "KPT":
            query_embeds = self.query_embedding(reference_embed)  # (B, 799, pt_feat_dim)
        elif self.query_type == "MVP":
            query_embeds = self.query_embedding(global_feat + reference_embed)
        elif self.query_type == "METRO":
            query_embeds = self.query_embedding(torch.cat([
                global_feat,
                template_mesh,
            ], dim=-1))  # (B, 799, pt_feat_dim)
        else:
            raise ValueError(f"no such query_type: {self.query_type}")
        return query_embeds

    def forward(self, mlvl_feat, img_metas, reference_points, template_mesh, **kwargs):
        results = dict()
        x = mlvl_feat
        batch_size, num_cams = x.size(0), x.size(1)

        global_feat = kwargs.get("global_feat", None)  # (BxN, 512)
        if global_feat != None:
            global_feat = self.layer_global_feat(global_feat)  # (BxN, 256)
            global_feat = global_feat.reshape(batch_size, num_cams, -1)  # (B, N, 256)
            global_feat = global_feat.sum(1)  # (B, 256) -> (B, 799, 256)
            global_feat = global_feat.unsqueeze(1).repeat(1, self.num_query, 1)

        inp_img_w, inp_img_h = img_metas["inp_img_shape"]  # (256, 256)
        # ref_mesh_gt = img_metas["ref_mesh_gt"]
        inp_res = torch.Tensor([inp_img_w, inp_img_h]).to(x.device).float()
        masks = x.new_zeros((batch_size, num_cams, inp_img_h, inp_img_w))
        x = self.input_proj(x.flatten(0, 1))
        x = x.view(batch_size, num_cams, *x.shape[-3:])  # [B, N, 256, H, W]
        feat_dim = x.size(2)
        assert feat_dim == self.pt_feat_dim, "self.pt_feat_dim should be equal to feat_dim"
        # interpolate masks to have the same spatial shape with x
        masks = F.interpolate(masks, size=x.shape[-2:]).to(torch.bool)

        coords_embed, coords3d, coords3d_abs, _ = self.position_embeding(mlvl_feat, img_metas, masks)

        sin_embed = self.positional_encoding(masks)
        sin_embed = self.adapt_pos3d(sin_embed.flatten(0, 1)).view(x.size())  # (B, N, 256, H, W)

        posi_embed = sin_embed + coords_embed
        x = x + posi_embed

        center_point = reference_points.mean(1).unsqueeze(1)  # [B, 1, 3]
        if self.center_shift == True:
            center_point = center_point + 0.01 * \
                           self.center_shift_layer(reference_points.transpose(1, 2)).transpose(1, 2)

        reference_embed = self.reference_embed.weight  # (799, 256)
        # reference_embed = pos2posemb3d(reference_embed)  # (799, 384)   384 <-- (self.embed_dims * 3 // 2)
        reference_embed = reference_embed.unsqueeze(0).expand(batch_size, -1, -1)  # (B, 799, 256)
        template_mesh = template_mesh.unsqueeze(0).expand(batch_size, -1, -1)  # template mesh  # (B, 799, 3)

        ref_proj_2d = reference_points.unsqueeze(1).repeat(1, num_cams, 1, 1)

        # *  normalize reference points into position range
        reference_points[..., 0:1] = (reference_points[..., 0:1] - self.position_range[0]) / \
                                     (self.position_range[3] - self.position_range[0])
        reference_points[..., 1:2] = (reference_points[..., 1:2] - self.position_range[1]) / \
                                     (self.position_range[4] - self.position_range[1])
        reference_points[..., 2:3] = (reference_points[..., 2:3] - self.position_range[2]) / \
                                     (self.position_range[5] - self.position_range[2])

        query_embeds = self.generate_query(
            reference_embed=reference_embed,
            reference_points=reference_points,
            template_mesh=template_mesh,
            global_feat=global_feat,
        )  # (B, 799, pt_feat_dim)

        # coords3d: [B, N, 32, 32, 32, 3], coords3d_nsmaple: [B, nsample, 3]
        coords3d_abs = coords3d_abs.reshape(batch_size, -1, 3)
        randlist = torch.randperm(coords3d_abs.size(1))
        coords3d_abs = coords3d_abs[:, randlist, :]
        coords3d_nsample = self.sample_points_from_ball_query(coords3d_abs, center_point, self.nsample, self.radius)
        pt_xyz = coords3d_nsample
        # coords3d_nsample -> [B, N, nsample, 3], coords3d_nsample_project: [B, N, nsample, 2]
        coords3d_nsample = coords3d_nsample.unsqueeze(1).repeat(1, num_cams, 1, 1)
        coords3d_nsample_project = batch_cam_extr_transf(torch.linalg.inv(img_metas["cam_extr"]), coords3d_nsample)
        coords3d_nsample_project = batch_cam_intr_projection(img_metas["cam_intr"], coords3d_nsample_project)
        # results["coords3d_nsample_project"] = coords3d_nsample_project.detach()
        coords3d_nsample_project = coords3d_nsample_project.flatten(0, 1).unsqueeze(-2)  # uv -> WH

        coords3d_nsample_project = torch.einsum("bijk, k->bijk", coords3d_nsample_project,
                                                1.0 / inp_res)  # TENSOR (B, N,  nsample, 2), [0 ~ 1]
        coords3d_nsample_project = coords3d_nsample_project * 2 - 1
        coords3d_project_invalid = (coords3d_nsample_project > 1.0) | (coords3d_nsample_project < -1.0)

        # NOTE: sanity check based on bugs reported Oct. 24
        ratio_invalid = torch.sum(coords3d_project_invalid) / torch.numel(coords3d_project_invalid)
        if ratio_invalid > 0.3 and ratio_invalid <= 0.5:
            logger.warning(f"Projection returns {torch.sum(coords3d_project_invalid)} / "
                           f"{torch.numel(coords3d_project_invalid)} outsiders in its resutls, "
                           f"may be a bug !")
        if ratio_invalid > 0.5:
            raise ValueError(f"Too many invalid projective points, "
                             f"consider redue the RADIUS_SAMPLE : {self.radius}, "
                             f"and check center_points's validness !")

        # pt_sampled_feats: [B, nsample, N, 256], sin_embed_sample: [B, nsample, N, 256]

        ref_proj_2d = batch_cam_extr_transf(torch.linalg.inv(img_metas["cam_extr"]), ref_proj_2d)
        ref_proj_2d = batch_cam_intr_projection(img_metas["cam_intr"], ref_proj_2d)
        ref_proj_2d = ref_proj_2d.flatten(0, 1).unsqueeze(-2)  # uv -> WH
        ref_proj_2d = torch.einsum("bijk, k->bijk", ref_proj_2d, 1.0 / inp_res)  # TENSOR (B, N,  nsample, 2), [0 ~ 1]
        ref_proj_2d = ref_proj_2d * 2 - 1

        query_feat = F.grid_sample(x.flatten(0, 1), ref_proj_2d, align_corners=False) \
            .squeeze(-1).reshape(batch_size, num_cams, feat_dim, self.num_query).permute(0, 3, 1, 2)
        pt_sampled_feats = F.grid_sample(x.flatten(0, 1), coords3d_nsample_project, align_corners=False) \
            .squeeze(-1).reshape(batch_size, num_cams, feat_dim, self.nsample).permute(0, 3, 1, 2)
        pt_smapled_emb = F.grid_sample(posi_embed.flatten(0, 1), coords3d_nsample_project, align_corners=False) \
            .squeeze(-1).reshape(batch_size, num_cams, feat_dim, self.nsample).permute(0, 3, 1, 2)
        if self.merge_mode == "attn":
            master_id = img_metas["master_id"]
            pt_sampled_feats = self.merge_features(pt_sampled_feats, self.merge_net_feature, master_id, batch_size)
            query_feat = self.merge_features(query_feat, self.merge_net_query_feature, master_id, batch_size)
        elif self.merge_mode == "sum":
            pt_sampled_feats = torch.sum(pt_sampled_feats, dim=-2)  # [B, nsample, 256]
            query_feat = torch.sum(query_feat, dim=-2)
        else:
            raise ValueError(f"CAM_FEAT_MERGE must in [attn, sum], default sum, got {self.merge_mode}")

        pt_smapled_emb = torch.sum(pt_smapled_emb, dim=-2)  # [B, nsample, 256]

        pt_xyz[..., 0:1] = (pt_xyz[..., 0:1] - self.position_range[0]) / \
                           (self.position_range[3] - self.position_range[0])
        pt_xyz[..., 1:2] = (pt_xyz[..., 1:2] - self.position_range[1]) / \
                           (self.position_range[4] - self.position_range[1])
        pt_xyz[..., 2:3] = (pt_xyz[..., 2:3] - self.position_range[2]) / \
                           (self.position_range[5] - self.position_range[2])

        interm_ref_pts = self.transformer(
            pt_xyz=pt_xyz,  # [B, 2048, 3]
            pt_feats=pt_sampled_feats,  # [B, 2048, 256]
            pt_embed=pt_smapled_emb,  # [B, 2048,256]
            query_feat=query_feat,
            query_emb=query_embeds,  # [B, 799, 256]
            query_xyz=reference_points,  # [B, 799, 3]
            reg_branches=self.reg_branches,
        )
        interm_ref_pts = torch.nan_to_num(interm_ref_pts)
        all_coords_preds = interm_ref_pts  # (N_Decoder, BS, NUM_QUERY, 3)

        # scale all the joitnts and vertices to the camera space
        # position_range [xmin, ymin, zmin, xmax, ymax, zmax]
        all_coords_preds[..., 0:1] = \
            all_coords_preds[..., 0:1] * (self.position_range[3] - self.position_range[0]) + self.position_range[0]
        all_coords_preds[..., 1:2] = \
            all_coords_preds[..., 1:2] * (self.position_range[4] - self.position_range[1]) + self.position_range[1]
        all_coords_preds[..., 2:3] = \
            all_coords_preds[..., 2:3] * (self.position_range[5] - self.position_range[2]) + self.position_range[2]

        results["all_coords_preds"] = all_coords_preds
        return results


@HEAD.register_module()
# class POEM_METROlikeHead(BasePointEmbedHead):
class POEM_woPoint_Head(BasePointEmbedHead):

    def __init__(self, cfg: CN):
        self.num_reg_fcs = cfg.NUM_REG_FCS
        self.pt_feat_dim = cfg.get("POINTS_FEAT_DIM", cfg.EMBED_DIMS)
        super(POEM_woPoint_Head, self).__init__(cfg)

    def _build_head_module(self):
        super()._build_head_module()

        if hasattr(self, "reg_branches"):
            logger.info("remove BasePointEmbedHead' s reg_branch")
            del self.reg_branches

        # Reg branch with shared weights
        reg_branch = []
        for _ in range(self.num_reg_fcs):
            reg_branch.append(nn.Linear(self.embed_dims, self.embed_dims))
            reg_branch.append(nn.ReLU())
        reg_branch.append(nn.Linear(self.embed_dims, 3))
        # reg_branch.append(nn.Sigmoid())
        reg_branch = nn.Sequential(*reg_branch)
        self.reg_branches = nn.ModuleList([reg_branch for _ in range(self.num_preds)])
        logger.warning(f"{type(self).__name__} build done")

    def _str_custom_args(self):
        str_ = super()._str_custom_args()
        return str_ + ", " + f"num_reg_fcs: {self.num_reg_fcs}"

    def init_weights(self):
        """Initialize weights of the transformer head."""
        # The initialization for transformer is important
        self.transformer.init_weights()
        nn.init.uniform_(self.reference_embed.weight.data, 0, 1)

    def forward(self, mlvl_feat, img_metas, reference_points, template_mesh, **kwargs):
        results = dict()
        x = mlvl_feat  # (B, N, 128, 32, 32)
        batch_size, num_cams = x.size(0), x.size(1)
        inp_img_w, inp_img_h = img_metas["inp_img_shape"]  # (256, 256)
        masks = x.new_zeros((batch_size, num_cams, inp_img_h, inp_img_w))
        x = self.input_proj(x.flatten(0, 1))
        x = x.view(batch_size, num_cams, *x.shape[-3:])
        # interpolate masks to have the same spatial shape with x
        masks = F.interpolate(masks, size=x.shape[-2:]).to(torch.bool)
        coords_embed, coords3d, coords3d_abs, _ = self.position_embeding(mlvl_feat, img_metas, masks)
        sin_embed = self.positional_encoding(masks)
        sin_embed = self.adapt_pos3d(sin_embed.flatten(0, 1)).view(x.size())
        pos_embed = coords_embed + sin_embed

        reference_embed = self.reference_embed.weight  # (799, 3)
        reference_embed = pos2posemb3d(reference_embed)  # (799, 384)   384 <-- (self.embed_dims * 3 // 2)
        reference_embed = reference_embed.unsqueeze(0).expand(batch_size, -1, -1)  # (B, 799, 384)
        template_mesh = template_mesh.unsqueeze(0).expand(batch_size, -1, -1)  # template mesh  # (B, 799, 3)

        # *  normalize reference points into position range
        reference_points[..., 0:1] = (reference_points[..., 0:1] - self.position_range[0]) / \
                                     (self.position_range[3] - self.position_range[0])
        reference_points[..., 1:2] = (reference_points[..., 1:2] - self.position_range[1]) / \
                                     (self.position_range[4] - self.position_range[1])
        reference_points[..., 2:3] = (reference_points[..., 2:3] - self.position_range[2]) / \
                                     (self.position_range[5] - self.position_range[2])

        query_embeds = self.query_embedding(torch.cat([
            reference_embed,
            reference_points,
            template_mesh,
        ], dim=-1))  # (B, 799, embed_dims=256)

        outs_dec, interm_ref_pts, _ = self.transformer(
            x=x,
            mask=masks,
            query_embed=query_embeds,
            pos_embed=pos_embed,
            reference_points=reference_points,
            reg_branch=self.reg_branches,
        )
        all_coords_preds = interm_ref_pts  # (N_Decoder, BS, NUM_QUERY, 3)
        # scale all the joitnts and vertices to the camera space
        # position_range [xmin, ymin, zmin, xmax, ymax, zmax]
        all_coords_preds[..., 0:1] = \
            all_coords_preds[..., 0:1] * (self.position_range[3] - self.position_range[0]) + self.position_range[0]
        all_coords_preds[..., 1:2] = \
            all_coords_preds[..., 1:2] * (self.position_range[4] - self.position_range[1]) + self.position_range[1]
        all_coords_preds[..., 2:3] = \
            all_coords_preds[..., 2:3] * (self.position_range[5] - self.position_range[2]) + self.position_range[2]

        results["all_coords_preds"] = all_coords_preds
        return results


@HEAD.register_module()
class mvf_head(BasePointEmbedHead):
    def __init__(self, cfg: CN):
        self.radius = cfg.RADIUS_SAMPLE
        # self.njoints = cfg.N_JOINTS
        self.nsample = cfg.get("N_SAMPLE", 21 * 20)
        self.view_nums = cfg.get("VIEW_NUMS", 8)
        self.pt_feat_dim = cfg.POINTS_FEAT_DIM  # 256
        self.merge_mode = cfg.get("CAM_FEAT_MERGE", "attn")  # By default, attention
        self.query_type = cfg.get("QUERY_TYPE", "UAM")
        self.PETR_embedding = cfg.get("PETR_EMBEDDING", False)
        self.parametric_output = cfg.TRANSFORMER.get("PARAMETRIC_OUTPUT", False)
        self.transformer_center_idx = cfg.TRANSFORMER.get("TRANSFORMER_CENTER_IDX", 9)
        super(mvf_head, self).__init__(cfg)

    def _build_head_module(self):
        super(mvf_head, self)._build_head_module()

        # Network G
        self.merge_net_feature = nn.ModuleList()
        self.merge_net_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims, self.embed_dims), nn.ReLU(),
                          nn.Linear(self.embed_dims, self.embed_dims // 2)))
        self.merge_net_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims // 2, self.embed_dims // 2), nn.ReLU(),
                          nn.Linear(self.embed_dims // 2, self.embed_dims)))
        self.merge_net_query_feature = nn.ModuleList()

        # Configuration for the merge net
        self.merge_net_query_feature = nn.ModuleList()
        self.merge_net_query_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims, self.embed_dims), nn.ReLU(),
                          nn.Linear(self.embed_dims, self.embed_dims // 2)))
        self.merge_net_query_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims // 2, self.embed_dims // 2), nn.ReLU(),
                          nn.Linear(self.embed_dims // 2, self.embed_dims)))

        self.layer_global_feat = nn.Linear(512, self.embed_dims)

        # self.reference_mv_embed = nn.Linear(280, 256)

        self.query_embedding = nn.Sequential(
            nn.Linear(self.embed_dims + 256 + 3, self.embed_dims),
            nn.ReLU(),
            nn.Linear(self.embed_dims, self.pt_feat_dim),
        )

        # Configuration for the query_feat_embedding
        self.query_feat_embedding = nn.Embedding(799, self.pt_feat_dim)  # (799, 256)

        # A mano layer for creating template mesh
        self.mano_layer = ManoLayer(joint_rot_mode="axisang",
                                    use_pca=False,
                                    mano_assets_root="assets/mano_v1_2",
                                    center_idx=self.transformer_center_idx,
                                    flat_hand_mean=True)

        self.view_embed = nn.Parameter(torch.zeros(1, self.view_nums, 1, self.embed_dims))
        # self.temp_embed = nn.Parameter(torch.zeros(1, self.maxlen, 1, self.embed_dims))
        self.pos_embed = nn.Parameter(torch.zeros(1, self.nsample, self.embed_dims))
        trunc_normal_(self.view_embed, std=.02)
        trunc_normal_(self.pos_embed, std=.02)

        logger.info(f"{type(self).__name__} got query_type: {self.query_type}")
        logger.warning(f"{type(self).__name__} build done")

    def _str_custom_args(self):
        str_ = super()._str_custom_args()
        return str_ + ", " + f"agg_merge_mode: {self.merge_mode}"

    def merge_features_mv(self, q, merge_net, master_id):
        """
            q: [B, nsample, N, 256]
            q_merged: [B, nsample, 256]
        """
        master_is_zero = torch.sum(master_id)
        assert master_is_zero == 0, "only support master_id is 0"
        cam_num = q.shape[2]

        q1 = q[:, :, 0, :]
        q = merge_net[0](q)
        master_features = q[:, :, 0, :]  # [B, nsample, 128]
        other_features = q[:, :, 1:, :]  # [B, nsample, 7, 128]
        q = torch.matmul(other_features, master_features.unsqueeze(-1))  # [B, nsample, 7, 1]
        q = torch.matmul(other_features.transpose(2, 3), q).squeeze(-1)
        q_merged = merge_net[1](q) / cam_num  # [B, nsample, 256]
        q_merged = q1 + q_merged
        return q_merged

    def generate_query(self, reference_embed, reference_points, reference_mv_feat):
        query_embeds = self.query_embedding(torch.cat([
            reference_embed,
            reference_points,
            reference_mv_feat,
        ], dim=-1))  # (B, 21, pt_feat_dim)
        return query_embeds

    def _debug_viz(self, debug_metas, src_points_sub, idx=0):
        # Visualize the first view
        img_single = debug_metas["img"][idx]
        image = img_single.detach().cpu().unsqueeze(0)
        image = bchw_2_bhwc(denormalize(image, [0.5, 0.5, 0.5], [1, 1, 1], inplace=False))
        image = image.mul_(255.0).view(1, 256, 256, 3).squeeze(0).numpy().astype(np.uint8)  # (B, H, W, 3)
        vis_points = src_points_sub[idx]
        viz_3d(image, vis_points)

    def forward(self, batch, inputs, **kwargs):
        results = dict()
        x = inputs['mlvl_feat']  # mlvl_feat := (BN, 128, 32, 32) / prev (B, N, 128, 32, 32)
        BT, N = x.shape[0], x.shape[1]

        anchor_joints = inputs['ref_joints']
        ambig_joints = inputs['ambig_ref_joints'].detach()
        anchor_center = anchor_joints[:, self.transformer_center_idx:self.transformer_center_idx + 1]

        # *  To center
        # pt_xyz = pt_xyz_rel + reference_hand_center
        # reference_points = reference_points_rel + reference_hand_center
        pt_xyz = ambig_joints
        reference_points = anchor_joints

        ref_pt_3d_in_cam = pt_xyz.unsqueeze(1).repeat(1, N, 1, 1)
        ref_query_3d_in_cam = reference_points.unsqueeze(1).repeat(1, N, 1, 1)

        inp_img_w, inp_img_h = inputs["inp_img_shape"]  # (256, 256)
        inp_res = torch.Tensor([inp_img_w, inp_img_h]).to(x.device).float()
        inputs["inp_res"] = inp_res
        masks = x.new_zeros((BT, N, inp_img_h, inp_img_w))
        x = self.input_proj(x.flatten(0, 1))  # (BTN, 128, 32, 32)

        x = x.view(BT, N, *x.shape[-3:])  # (BT, N, 256, H, W)
        feat_dim = x.size(2)
        assert feat_dim == self.pt_feat_dim, "self.pt_feat_dim should be equal to feat_dim"

        masks = F.interpolate(masks, size=x.shape[-2:]).to(torch.bool)

        coords_embed, _, _, _ = self.position_embeding(inputs, masks)

        sin_embed = self.positional_encoding(masks)
        sin_embed = self.adapt_pos3d(sin_embed.flatten(0, 1)).view(x.size())  # (B, N, 256, H, W)

        posi_embed = sin_embed + coords_embed
        x = x + posi_embed

        ref_pt_3d = batch_cam_extr_transf(torch.linalg.inv(inputs["cam_extr"]), ref_pt_3d_in_cam)
        ref_pt_2d = batch_cam_intr_projection(inputs["cam_intr"], ref_pt_3d)
        ref_pt_2d = ref_pt_2d.flatten(0, 1).unsqueeze(-2)  # uv -> WH
        ref_pt_2d = torch.einsum("bijk, k->bijk", ref_pt_2d, 1.0 / inp_res)  # TENSOR (B, N,  nsample, 2), [0 ~ 1]
        ref_pt_2d = ref_pt_2d * 2 - 1

        ref_query_3d = batch_cam_extr_transf(torch.linalg.inv(inputs["cam_extr"]), ref_query_3d_in_cam)
        ref_query_2d = batch_cam_intr_projection(inputs["cam_intr"], ref_query_3d)
        ref_query_2d = ref_query_2d.flatten(0, 1).unsqueeze(-2)  # uv -> WH
        ref_query_2d = torch.einsum("bijk, k->bijk", ref_query_2d, 1.0 / inp_res)  # TENSOR (B, N,  nsample, 2), [0 ~ 1]
        ref_query_2d = ref_query_2d * 2 - 1

        pt_sampled_feats = F.grid_sample(x.flatten(0, 1), ref_pt_2d, align_corners=False).squeeze(-1).reshape(BT, N,
                                                                                                              feat_dim,
                                                                                                              self.nsample).permute(
            0, 3, 1, 2)
        pt_smapled_emb = F.grid_sample(posi_embed.flatten(0, 1), ref_pt_2d, align_corners=False) \
            .squeeze(-1).reshape(BT, N, feat_dim, self.nsample).permute(0, 3, 1, 2)
        pt_merged_feats = self.merge_features_mv(pt_sampled_feats, self.merge_net_feature,
                                                 torch.cat(batch['master_id'], dim=0))

        query_sampled_feats = F.grid_sample(x.flatten(0, 1), ref_query_2d, align_corners=False).squeeze(-1).reshape(BT,
                                                                                                                    N,
                                                                                                                    feat_dim,
                                                                                                                    self.num_query).permute(
            0, 3, 1, 2)
        query_sampled_emb = F.grid_sample(posi_embed.flatten(0, 1), ref_query_2d, align_corners=False) \
            .squeeze(-1).reshape(BT, N, feat_dim, self.num_query).permute(0, 3, 1, 2)
        query_merged_feats = self.merge_features_mv(query_sampled_feats, self.merge_net_query_feature,
                                                    torch.cat(batch['master_id'], dim=0))

        pt_smapled_emb = torch.sum(pt_smapled_emb, dim=-2)  # [B, nsample, 256]
        query_sampled_emb = torch.sum(query_sampled_emb, dim=-2)  # [B, nquery, 256]

        # query_feat = reference_mv_feat + query_merged_feats  # (B, 21, 256)
        # query_feat = query_feat + query_embeds  # (B, 799, 256)

        # normalize pt_xyz to [-1, 1] and bps_xyz to [-1, 1]
        # pt_xyz = (pt_xyz - reference_hand_center) / self.radius
        # reference_points = (reference_points - reference_hand_center) / self.radius
        pt_xyz = (pt_xyz - anchor_center) / self.radius
        reference_points = (reference_points - anchor_center) / self.radius

        # Now the transformer can be trained in batches.
        interm_ref_joints_list, mano_joints, mano_verts, pred_mano_params = self.transformer(
            pt_xyz=pt_xyz,  # [BT, 420, 3]
            pt_feats=pt_merged_feats,  # [BT, 420, 256]
            pt_embed=pt_smapled_emb,
            query_feat=query_merged_feats,  # [BT, 21, 256]
            query_xyz=reference_points,  # [BT, 21, 3]
            query_emb=query_sampled_emb,
        )

        all_joints_preds = torch.nan_to_num(interm_ref_joints_list)
        pred_joints = torch.nan_to_num(mano_joints)
        pred_verts = torch.nan_to_num(mano_verts)
        # all_joints_preds = interm_ref_joints  # (NUM_TRANSFORMER_BLOCKS, BS, 21, 3)
        master_joints_preds = pred_joints  # (NUM_TRANSFORMER_BLOCKS, BS, 21, 3)
        master_verts_preds = pred_verts  # (NUM_TRANSFORMER_BLOCKS, BS, 778, 3)

        # scale all the joints and vertices to the camera space for non-parametric-case and the preds back and add the offsetm
        # reference_hand_center = reference_hand_center.unsqueeze(1).unsqueeze(0) # (1, B, 1, 3)

        # Only the last layer returns the unscaled result, so previous layers still need to be scaled back
        all_joints_preds = all_joints_preds * self.radius + anchor_center.unsqueeze(0)
        # We won't make the scale for the last layer as it returns the result from mano layer
        master_joints_preds = master_joints_preds * self.radius + anchor_center
        master_verts_preds = master_verts_preds * self.radius + anchor_center

        if pred_mano_params is not None:
            # 1. 获取 BBox size。根据你的 ptEmb_transformer.py，ManoDecoder 的 bbox_3d_size 默认设为 0.4
            bbox_3d_size = 0.4
            if hasattr(self.transformer, 'decoder') and hasattr(self.transformer.decoder, 'bbox_3d_size'):
                bbox_3d_size = self.transformer.decoder.bbox_3d_size

            # 2. 计算全局缩放因子
            global_scale = (2.0 * self.radius) / bbox_3d_size

            # 3. 提取全局平移 (去掉中间的维度变为 [BT, 3])
            global_trans = anchor_center.squeeze(1)

            # 4. 封装进参数字典
            pred_mano_params['global_scale'] = global_scale
            pred_mano_params['global_trans'] = global_trans

        results['joints_preds_list'] = all_joints_preds[:-1, :, :, :]
        # results['joints_preds_list'] = interm_ref_joints_list
        results['master_mano_keypoints_mv'] = master_joints_preds  # (B, 21, 3)
        results["master_mano_verts_mv"] = master_verts_preds
        results["pred_mano_params_mv"] = pred_mano_params
        # results["coord_uv_mv"] = coord_uv

        return results